[package]
name = "some-scheme-compiler"
version = "0.1.0"
authors = ["Ben Simms <ben@bensimms.moe>"]

[dependencies]
nom = "4.1.1"
itertools = "0.7.8"
derive_more = "0.13.0"
structopt = "0.2"
failure = "0.1.3"
tempdir = "0.3.7"
include_dir = "0.2.1"
